apiVersion: v1
kind: Pod
metadata:
 name: go-test1
 labels:
   app: go-test1
   type: demo
spec:
 containers:
   - name: go-test1
     image: localhost:5000/go-test1
     ports:
       - containerPort: 8000
---
apiVersion: v1
kind: Pod
metadata:
 name: go-test2
 labels:
   app: go-test2
   type: demo
spec:
 containers:
   - name: go-test2
     image: localhost:5000/go-test2
     ports:
       - containerPort: 8000